version: '3'

services:
  webapp:
    build: .
    ports:
      - "8082:80"
    networks:
      - web-mysql-net

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: clave123
    ports:
      - "3307:3306"
    networks:
      - web-mysql-net

networks:
  web-mysql-net:
    driver: bridge
